/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Serve the built single-page workstation.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Activity
         * @description SSE: ``snapshot``, then ``run_added/run_updated`` + ``job_*`` diffs each poll tick.
         *
         *     ``max_events`` bounds the stream for tests/diagnostics; browsers omit it and stream forever.
         */
        get: operations["stream_activity_api_activity_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles
         * @description Point-in-time candles for ``symbol`` (``{symbol:path}`` so ``BTC/USD`` works).
         */
        get: operations["candles_api_candles__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Commands
         * @description The CLI command tree, each annotated with the run-type dir it writes (``None`` = no run).
         */
        get: operations["commands_api_commands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description All known jobs (live + this-session-finished), newest first.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Launch Job
         * @description Launch ``alpha <command> <args>`` as a background job. Returns its id + initial status.
         */
        post: operations["launch_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description A single job's status + its buffered output lines (for a late-opening panel).
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Job
         * @description Cancel a running job (idempotent no-op if already finished).
         */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job
         * @description SSE of a job's output; a reconnect with ``Last-Event-ID`` replays only the missed lines.
         */
        get: operations["stream_job_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options/curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options Curve
         * @description Price + greeks across a spot range for the greeks-vs-spot chart.
         */
        get: operations["options_curve_api_options_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options/greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options Greeks
         * @description Price + delta/gamma/vega/theta/rho for one European option.
         */
        get: operations["options_greeks_api_options_greeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options/iv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options Iv
         * @description The implied volatility that reprices the option to ``price`` (+ greeks at that vol).
         */
        get: operations["options_iv_api_options_iv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Research Compare
         * @description Backtest each strategy on ``symbol`` and rank by total return (slow — runs the engine).
         */
        get: operations["research_compare_api_research_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Scenario
         * @description Vol-scaling + tail-shock scenarios for a run (422 if it has no equity curve).
         */
        get: operations["risk_scenario_api_risk_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Filtered, newest-first, paginated run index for the run browser.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Detail
         * @description Full manifest + kind/mtime + artifact-presence flags.
         */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Equity
         * @description The run's equity curve as ``{ts, equity, drawdown}`` (empty lists when it wrote none).
         */
        get: operations["run_equity_api_runs__run_id__equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Forecast
         * @description A forecast run's history + forecast series (+ quantile bands). 404 otherwise.
         */
        get: operations["run_forecast_api_runs__run_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/forecast/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Forecast Paths
         * @description The first ``n`` (clamped to 40) sampled close paths of a forecast run. 404 otherwise.
         */
        get: operations["run_forecast_paths_api_runs__run_id__forecast_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/nulls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Nulls
         * @description A gauntlet run's raw per-tier null distributions. 404 when it wrote none.
         */
        get: operations["run_nulls_api_runs__run_id__nulls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Origins
         * @description A forecast-eval run's per-origin skill scores, columnar. 404 when it wrote none.
         */
        get: operations["run_origins_api_runs__run_id__origins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/propfirm-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Propfirm Paths
         * @description A prop-firm run's per-path Monte-Carlo outcomes, columnar. 404 when it wrote none.
         */
        get: operations["run_propfirm_paths_api_runs__run_id__propfirm_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tearsheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Tearsheet
         * @description The run's rendered quantstats tear sheet (embedded in Run Detail via an iframe).
         */
        get: operations["run_tearsheet_api_runs__run_id__tearsheet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trades
         * @description The run's trade-log rows (``[]`` when it wrote none).
         */
        get: operations["run_trades_api_runs__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trials
         * @description A sweep's per-config OOS return streams. 404 when it wrote none.
         */
        get: operations["run_trials_api_runs__run_id__trials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screener News
         * @description Recent company news for ``symbol`` (503 when unconfigured).
         */
        get: operations["screener_news_api_screener_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screener Quote
         * @description A live quote for ``symbol`` (503 when the finnhub key/network is missing).
         */
        get: operations["screener_quote_api_screener_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Strategies
         * @description Registered strategies + their tunable ``--param`` axes.
         */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Symbols
         * @description Every symbol with stored bars.
         */
        get: operations["symbols_api_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspaces
         * @description Every saved workspace (``{slug, name, updated}``).
         */
        get: operations["list_workspaces_api_workspaces_get"];
        put?: never;
        /**
         * Save Workspace
         * @description Save (upsert) a workspace under a slug derived from its name.
         */
        post: operations["save_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace
         * @description The full workspace document to restore.
         */
        get: operations["get_workspace_api_workspaces__slug__get"];
        put?: never;
        post?: never;
        /**
         * Delete Workspace
         * @description Delete a workspace (idempotent).
         */
        delete: operations["delete_workspace_api_workspaces__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workstation
         * @description Alias for the workstation (same SPA as ``/``).
         */
        get: operations["workstation_app_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candle */
        Candle: {
            /** C */
            c: number;
            /** H */
            h: number;
            /** L */
            l: number;
            /** O */
            o: number;
            /** T */
            t: number;
            /** V */
            v: number;
        };
        /** Candles */
        Candles: {
            /** Bars */
            bars: components["schemas"]["Candle"][];
            /** Snapshot Id */
            snapshot_id: string | null;
            /** Symbol */
            symbol: string;
        };
        /** CommandArgument */
        CommandArgument: {
            /** Name */
            name: string;
            /** Nargs */
            nargs: number;
            /** Required */
            required: boolean;
            /** Type */
            type: string;
        };
        /** CommandDefinition */
        CommandDefinition: {
            /** Args */
            args: components["schemas"]["CommandArgument"][];
            /** Id */
            id: string;
            /** Options */
            options: components["schemas"]["CommandOption"][];
            /** Run Type */
            run_type: string | null;
        };
        /** CommandOption */
        CommandOption: {
            /** Choices */
            choices: string[] | null;
            /** Default */
            default: string | number | boolean | string[] | null;
            /** Flag */
            flag: string | null;
            /** Help */
            help: string;
            /** Multiple */
            multiple: boolean;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Type */
            type: string;
        };
        /** Deleted */
        Deleted: {
            /** Deleted */
            deleted: string;
        };
        /** EquitySeries */
        EquitySeries: {
            /** Drawdown */
            drawdown: number[];
            /** Equity */
            equity: number[];
            /** Ts */
            ts: number[];
        };
        /** ForecastOrigins */
        ForecastOrigins: {
            /** Cover50 */
            cover50: boolean[];
            /** Cover80 */
            cover80: boolean[];
            /** Cover90 */
            cover90: boolean[];
            /** Crps */
            crps: number[];
            /** Crps Bootstrap */
            crps_bootstrap: number[];
            /** Crps Rw */
            crps_rw: number[];
            /** Hit */
            hit: boolean[];
            /** Median End Return */
            median_end_return: number[];
            /** Origin Ts */
            origin_ts: number[];
            /** Pre Cutoff */
            pre_cutoff: boolean[];
            /** Realized End Return */
            realized_end_return: number[];
        };
        /** ForecastPath */
        ForecastPath: {
            /** Closes */
            closes: number[];
            /** Sample */
            sample: number;
        };
        /** ForecastPaths */
        ForecastPaths: {
            /** Samples */
            samples: components["schemas"]["ForecastPath"][];
            /** Ts */
            ts: number[];
        };
        /** ForecastSeries */
        ForecastSeries: {
            /** Forecast */
            forecast: number[];
            /** Forecast Ts */
            forecast_ts: number[];
            /** History */
            history: number[];
            /** History Ts */
            history_ts: number[];
            /** Mean */
            mean: number[];
            /** P10 */
            p10: number[];
            /** P90 */
            p90: number[];
            /** Q25 */
            q25: number[];
            /** Q75 */
            q75: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            /** Command */
            command: string;
            /** Created At */
            created_at: number;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string | null;
            /** Lines */
            lines: string[];
            /** N Lines */
            n_lines: number;
            /** Returncode */
            returncode: number | null;
            /** Run Id */
            run_id: string | null;
            /** Status */
            status: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** JobSummary */
        JobSummary: {
            /** Command */
            command: string;
            /** Created At */
            created_at: number;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string | null;
            /** N Lines */
            n_lines: number;
            /** Returncode */
            returncode: number | null;
            /** Run Id */
            run_id: string | null;
            /** Status */
            status: string;
        };
        /**
         * LaunchRequest
         * @description Launch body: a command path (e.g. ``"backtest run"``) + its remaining args, or a bare
         *     ``args`` string (empty ``command``) for the free-form console.
         */
        LaunchRequest: {
            /**
             * Args
             * @default
             */
            args: string;
            /**
             * Command
             * @default
             */
            command: string;
        };
        /** NullTier */
        NullTier: {
            /** Statistics */
            statistics: number[];
            /** Tier */
            tier: string;
        };
        /** NullTiers */
        NullTiers: {
            /** Tiers */
            tiers: components["schemas"]["NullTier"][];
        };
        /** OptimTrial */
        OptimTrial: {
            /** Returns */
            returns: number[];
            /** Trial */
            trial: number;
        };
        /** OptimTrials */
        OptimTrials: {
            /** Trials */
            trials: components["schemas"]["OptimTrial"][];
        };
        /** OptionCurve */
        OptionCurve: {
            /** Days */
            days: number;
            /** Kind */
            kind: string;
            /** Points */
            points: components["schemas"]["OptionCurvePoint"][];
            /** Rate */
            rate: number;
            /** Strike */
            strike: number;
            /** Vol */
            vol: number;
        };
        /** OptionCurvePoint */
        OptionCurvePoint: {
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Price */
            price: number;
            /** Spot */
            spot: number;
            /** Theta */
            theta: number;
            /** Vega */
            vega: number;
        };
        /** OptionGreeks */
        OptionGreeks: {
            /** Days */
            days: number;
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Implied Vol */
            implied_vol?: number | null;
            /** Kind */
            kind: string;
            /** Market Price */
            market_price?: number | null;
            /** Price */
            price: number;
            /** Rate */
            rate: number;
            /** Rho */
            rho: number;
            /** Spot */
            spot: number;
            /** Strike */
            strike: number;
            /** Theta */
            theta: number;
            /** Vega */
            vega: number;
            /** Vol */
            vol: number;
        };
        /** ParamDefinition */
        ParamDefinition: {
            /** Default */
            default: number;
            /** Help */
            help: string;
            /** Max */
            max: number | null;
            /** Max Exclusive */
            max_exclusive: boolean;
            /** Min */
            min: number | null;
            /** Min Exclusive */
            min_exclusive: boolean;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** PropfirmPathColumns */
        PropfirmPathColumns: {
            /** Busted */
            busted: boolean[];
            /** Days To Pass */
            days_to_pass: (number | null)[];
            /** Passed */
            passed: boolean[];
            /** Payout */
            payout: number[];
        };
        /** PropfirmPaths */
        PropfirmPaths: {
            paths: components["schemas"]["PropfirmPathColumns"];
        };
        /** ResearchReport */
        ResearchReport: {
            /** N Bars */
            n_bars: number;
            /** Ranked */
            ranked: components["schemas"]["ResearchRow"][];
            /** Symbol */
            symbol: string;
        };
        /** ResearchRow */
        ResearchRow: {
            /** Error */
            error: string | null;
            /** Final Equity */
            final_equity?: number | null;
            /** N Trades */
            n_trades?: number | null;
            /** Strategy */
            strategy: string;
            /** Total Return */
            total_return: number | null;
        };
        /** RiskReport */
        RiskReport: {
            /** Confidence */
            confidence: number;
            /** Run Id */
            run_id: string;
            /** Scenarios */
            scenarios: components["schemas"]["RiskScenario"][];
        };
        /** RiskScenario */
        RiskScenario: {
            /** Annual Vol */
            annual_vol: number;
            /** Expected Shortfall */
            expected_shortfall: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Name */
            name: string;
            /** Sharpe */
            sharpe: number | null;
            /** Total Return */
            total_return: number;
            /** Value At Risk */
            value_at_risk: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Has Equity */
            has_equity: boolean;
            /** Has Forecast */
            has_forecast: boolean;
            /** Has Forecast Paths */
            has_forecast_paths: boolean;
            /** Has Nulls */
            has_nulls: boolean;
            /** Has Origins */
            has_origins: boolean;
            /** Has Propfirm Paths */
            has_propfirm_paths: boolean;
            /** Has Tearsheet */
            has_tearsheet: boolean;
            /** Has Trades */
            has_trades: boolean;
            /** Has Trials */
            has_trials: boolean;
            /** Kind */
            kind: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Mtime */
            mtime: number;
            /** Run Id */
            run_id: string;
        };
        /** RunList */
        RunList: {
            /** Items */
            items: components["schemas"]["RunListItem"][];
            /** Total */
            total: number;
        };
        /** RunListItem */
        RunListItem: {
            /** Command */
            command: string | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string | null;
            /** Mtime */
            mtime: number;
            /** Passed */
            passed: boolean | null;
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string | null;
            /** Symbols */
            symbols: string[] | null;
            /** Verdict */
            verdict: string | null;
        };
        /** ScreenerNews */
        ScreenerNews: {
            /** Items */
            items: components["schemas"]["ScreenerNewsItem"][];
            /** Symbol */
            symbol: string;
        };
        /** ScreenerNewsItem */
        ScreenerNewsItem: {
            /** Datetime */
            datetime: number;
            /** Headline */
            headline: string;
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Url */
            url: string;
        };
        /** ScreenerQuote */
        ScreenerQuote: {
            /** Change */
            change: number;
            /** Current */
            current: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Percent Change */
            percent_change: number;
            /** Prev Close */
            prev_close: number;
            /** Symbol */
            symbol: string;
        };
        /** StrategyDefinition */
        StrategyDefinition: {
            /** Has Tier1 Surrogate */
            has_tier1_surrogate: boolean;
            /** Name */
            name: string;
            /** Params */
            params: components["schemas"]["ParamDefinition"][];
        };
        /** Symbols */
        Symbols: {
            /** Symbols */
            symbols: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceBody
         * @description A workspace to save: a display name, the linked context, and the Dockview layout.
         */
        WorkspaceBody: {
            /** Dockview */
            dockview: {
                [key: string]: unknown;
            };
            /** @default {} */
            linked_context: components["schemas"]["WorkspaceLinkedContext"];
            /** Name */
            name: string;
        };
        /** WorkspaceDocument */
        WorkspaceDocument: {
            /** Dockview */
            dockview: {
                [key: string]: unknown;
            };
            linked_context: components["schemas"]["WorkspaceLinkedContext"];
            /** Name */
            name: string;
            /** Updated */
            updated?: number | null;
        };
        /** WorkspaceLinkedContext */
        WorkspaceLinkedContext: {
            /** End */
            end?: string | null;
            /** Runid */
            runId?: string | null;
            /** Start */
            start?: string | null;
            /** Symbol */
            symbol?: string | null;
        };
        /** WorkspaceMeta */
        WorkspaceMeta: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Updated */
            updated: number | null;
        };
        /** WorkspaceSaved */
        WorkspaceSaved: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_activity_api_activity_stream_get: {
        parameters: {
            query?: {
                poll?: number;
                max_events?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candles_api_candles__symbol__get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                snapshot?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commands_api_commands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandDefinition"][];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
    launch_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_api_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_curve_api_options_curve_get: {
        parameters: {
            query: {
                strike: number;
                vol: number;
                days?: number;
                rate?: number;
                kind?: string;
                width?: number;
                points?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionCurve"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_greeks_api_options_greeks_get: {
        parameters: {
            query: {
                spot: number;
                strike: number;
                vol: number;
                days?: number;
                rate?: number;
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionGreeks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_iv_api_options_iv_get: {
        parameters: {
            query: {
                spot: number;
                strike: number;
                price: number;
                days?: number;
                rate?: number;
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionGreeks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_compare_api_research_compare_get: {
        parameters: {
            query: {
                symbol: string;
                strategies?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_scenario_api_risk_scenario_get: {
        parameters: {
            query: {
                run_id: string;
                confidence?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                symbol?: string | null;
                verdict?: string | null;
                passed?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_equity_api_runs__run_id__equity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquitySeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_forecast_api_runs__run_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_forecast_paths_api_runs__run_id__forecast_paths_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPaths"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_nulls_api_runs__run_id__nulls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NullTiers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_origins_api_runs__run_id__origins_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastOrigins"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_propfirm_paths_api_runs__run_id__propfirm_paths_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropfirmPaths"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_tearsheet_api_runs__run_id__tearsheet_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trades_api_runs__run_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trials_api_runs__run_id__trials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimTrials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screener_news_api_screener_news_get: {
        parameters: {
            query: {
                symbol: string;
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerNews"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screener_quote_api_screener_quote_get: {
        parameters: {
            query: {
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerQuote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDefinition"][];
                };
            };
        };
    };
    symbols_api_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Symbols"];
                };
            };
        };
    };
    list_workspaces_api_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMeta"][];
                };
            };
        };
    };
    save_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSaved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_workspaces__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_api_workspaces__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workstation_app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
