// Public aliases over the generated OpenAPI component definitions.

import type { components } from './generated'

type Schema = components['schemas']

export type RunContextV1 =
  | { schema_version: 1; kind: 'governed_project'; project_id: string }
  | { schema_version: 1; kind: 'standalone_sandbox' }

export type RunListItem = Schema['RunListItem']
export type RunList = Schema['RunList']
export type RunDetail = Schema['RunDetail']
export type EquitySeries = Schema['EquitySeries']
export type ForecastSeries = Schema['ForecastSeries']
export type NullTiers = Schema['NullTiers']
export type OptimTrials = Schema['OptimTrials']
export type PropfirmPaths = Schema['PropfirmPaths']
export type ForecastOrigins = Schema['ForecastOrigins']
export type Candle = Schema['Candle']
export type CandleProvenance = Schema['CandleProvenance']
export type Candles = Schema['Candles']
export type PaperCandleMarker = Schema['PaperCandleMarker']
export type ParamSpec = Schema['ParamDefinition']
export type StrategyDef = Schema['StrategyDefinition']
export type CommandOption = Schema['CommandOption']
export type CommandArg = Schema['CommandArgument']
export type CommandDef = Schema['CommandDefinition']
export type JobSummary = Schema['JobSummary']
export type JobDetail = Schema['JobDetail']
export type CryptoFamily = Schema['CryptoFamilyValue']
export type CryptoCatalog = Schema['CryptoCatalogResponse']
export type CryptoCapabilities = Schema['CryptoCapabilitiesResponse']
export type CryptoCapabilityItem = Schema['CryptoCapabilityItem']
export type CryptoStorage = Schema['CryptoStorageResponse']
export type CryptoStorageInventory = Schema['CryptoStorageInventoryResponse']
export type CryptoStorageVerify = Schema['CryptoStorageVerifyResponse']
export type CryptoCacheClean = Schema['CryptoCacheCleanResponse']
export type CryptoCoverage = Schema['CryptoCoverageResponse']
export type CryptoCoverageItem = Schema['CryptoCoverageItem']
export type CryptoAssetIdentity = Schema['CryptoAssetIdentityResponse']
export type CryptoAssetMaster = Schema['CryptoAssetMasterResponse']
export type CryptoAssetMasters = Schema['CryptoAssetMasterListResponse']
export type CryptoQuality = Schema['CryptoQualityResponse']
export type CryptoFeatureName = Schema['CryptoFeatureNameValue']
export type CryptoFeatureCreateRequest = Schema['CryptoFeatureCreateRequest']
export type CryptoFeature = Schema['CryptoFeatureResponse']
export type CryptoFeatures = Schema['CryptoFeatureListResponse']
export type CryptoCoverageCadence = Schema['CryptoCoverageCadenceValue']
export type CryptoCoverageTask = Schema['CryptoCoverageTaskResponse']
export type CryptoCoverageProfileSummary = Schema['CryptoCoverageProfileSummaryResponse']
export type CryptoCoverageProfiles = Schema['CryptoCoverageProfileListResponse']
export type CryptoCoverageProfile = Schema['CryptoCoverageProfileCreateResponse']
export type CryptoCoverageProfilePage = Schema['CryptoCoverageProfilePageResponse']
export type CryptoCoverageBatch = Schema['CryptoCoverageBatchResponse']
export type CryptoCoverageBatches = Schema['CryptoCoverageBatchListResponse']
export type CryptoLiquidityMembership = Schema['CryptoLiquidityFreezeResponse']
export type CryptoOneMinuteSelection = Schema['CryptoOneMinuteSelectionResponse']
export type CryptoEstimateRequest = Schema['CryptoEstimateRequest']
export type CryptoEstimate = Schema['CryptoEstimateResponse']
export type CryptoAcquisitionRequest = Schema['CryptoAcquisitionRequest']
export type CryptoSnapshotCreate = Schema['CryptoSnapshotCreateResponse']
export type CryptoSnapshotVerifyRequest = Schema['CryptoSnapshotVerifyRequest']
export type CryptoSnapshotVerify = Schema['CryptoSnapshotVerifyResponse']
export type CryptoSnapshotRegister = Schema['CryptoSnapshotRegisterResponse']
export type WorkspaceMeta = Schema['WorkspaceMeta']
export type WorkspaceDoc = Schema['WorkspaceDocument']
export type RunComparison = Schema['RunComparisonResponse']
export type FigureCatalogue = Schema['FigureCatalogue']
export type FigureCatalogueItem = Schema['FigureCatalogueItem']
export type FigureMetadata = Schema['FigureMetadata']
export type FigurePanelMeta = Schema['FigurePanelMeta']
export type RiskScenario = Schema['RiskScenario']
export type RiskReport = Schema['RiskReport']
export type ScreenerQuote = Schema['ScreenerQuote']
export type ScreenerNewsItem = Schema['ScreenerNewsItem']
export type ScreenerNews = Schema['ScreenerNews']
export type ResearchRow = Schema['ResearchRow']
export type ResearchReport = Schema['ResearchReport']
export type ResearchCase = Schema['ResearchCase']
export type ResearchStudyStatusV1 = Schema['ResearchStudyStatusV1']
export type VerifiedBlindSemanticReadV1 = Schema['VerifiedBlindSemanticReadV1']
export type ResearchCaptureRequest = Schema['ResearchCaptureRequest']
export type ResearchCaptureResponse = Schema['ResearchCaptureResponse']
export type ResearchMaterialAnswers = Schema['ResearchMaterialAnswers']
export type ResearchProposalRequest = Schema['ResearchProposalRequest']
export type ResearchProposalOptionsV1 = Schema['ResearchProposalOptionsV1']
export type ResearchProposalResponse = Schema['ResearchProposalResponse']
export type ResearchLaunchResponse = Schema['ResearchLaunchResponse']
export type ResearchProgressReport = Schema['ResearchProgressReport']
export type ResearchGatePacket = Schema['ResearchGatePacket']
export type ResearchCaseReport = Schema['ResearchCaseReport']
export type ResearchCasePage = Schema['ResearchCasePage']
export type ResearchCaseSummaryRow = Schema['ResearchCaseSummaryRow']
export type ResearchEvidenceHub = Schema['ResearchEvidenceHub']
export type ResearchEvidenceHubSections = Schema['ResearchEvidenceHubSections']
export type ResearchScorecard = Schema['ResearchScorecard']
export type ResearchChecklistQuestion = Schema['ResearchChecklistQuestion']
export type ResearchEdgeChecklist = Schema['ResearchEdgeChecklist']
export type ResearchDecisionHistoryEvent = Schema['ResearchDecisionHistoryEvent']
export type ResearchDecisionView = Schema['ResearchDecisionView']
export type HypothesisCard = Schema['HypothesisCard']
export type ResearchContextPacket = Schema['ResearchContextPacket']
export type ResearchContextPacketPage = Schema['ResearchContextPacketPage']
export type ResearchNote = Schema['ResearchNote']
export type ResearchNotePage = Schema['ResearchNotePage']
export type ResearchProtocolEntry = Schema['ResearchProtocolEntry']
export type ResearchProtocolLibrary = Schema['ResearchProtocolLibrary']
export type ResearchDatasetRefRow = Schema['ResearchDatasetRefRow']
export type ResearchDatasetPage = Schema['ResearchDatasetPage']
export type OptionGreeks = Schema['OptionGreeks']
export type OptionCurvePoint = Schema['OptionCurvePoint']
export type OptionCurve = Schema['OptionCurve']
export type ProviderCredential = Schema['CredentialStatus']
export type ProviderOption = Schema['ProviderOption']
export type ProviderDefinition = Schema['ProviderDefinition']
export type ProviderCheckReceipt = Schema['ProviderCheckReceipt']
export type SystemStatus = Schema['SystemStatus']
export type JsonScalar = Schema['JsonScalar']
export type PaperSession = Schema['PaperSession']
export type PaperStatus = PaperSession['status']
export type PaperEvent = Schema['PaperEvent']
export type PaperEventType = PaperEvent['event_type']
export type PaperReadinessReport = Schema['PaperReadinessReport']
export type PaperJobSummary = JobSummary

// Intentionally opaque: trade schemas vary by engine and remain manifest-adjacent rows.
export type TradeRow = Record<string, string | number | null>

// Workstation-v3 contracts come directly from the committed OpenAPI snapshot. The native
// provenance payload is the one intentionally open JSON object; narrow it to the CLI fields the
// panel reads while keeping all numeric series generated.
export type ForecastPath = Schema['ForecastPath']
export type ForecastPaths = Schema['ForecastPaths']
export type ChartTrade = Schema['ChartTrade']
export type ChartTraceEvent = Schema['ChartTraceEvent']
export type ChartIndicator = Schema['ChartIndicator']
export type ChartAnnotation = Schema['ChartAnnotation']
export type ChartBundle = Schema['ChartBundle']
export type NativeCalendarReturn = Schema['NativeCalendarReturn']
export type NativeYearlyReturn = Schema['NativeYearlyReturn']
export type NativeHistogramBin = Schema['NativeHistogramBin']
export type NativeQqPoint = Schema['NativeQQPoint']
export type NativeRollingPoint = Schema['NativeRollingMetric']
export type NativeTearSheetProjection = Omit<Schema['NativeTearSheetResponse'], 'provenance'> & {
  provenance: {
    run_id: string
    metric_namespace: string
    artifact_contract_version: number | null
    artifact_sha256: Record<string, string>
  }
}
export type PortfolioAllocationRow = Schema['PortfolioAllocationRow']
export type PortfolioCorrelationRow = Schema['PortfolioCorrelationRow']
export type PortfolioAnalyticsProjection = Schema['PortfolioAnalyticsResponse']
export type StageState = Schema['StageStateValue']
export type DevelopmentStage = Schema['StageLinkCreateRequest']['stage']
export type ProjectSummary = Schema['ProjectSummary']
export type ProjectPage = Schema['ProjectPage']
export type StrategyVersion = Schema['StrategyVersion']
export type ExperimentSpec = Schema['ExperimentSpec']
export type StageRunLink = Schema['StageRunLink']
export type AttemptRecord = Schema['AttemptRecord']
export type HoldoutState = Schema['HoldoutState']
export type DecisionPacket = Schema['DecisionPacket']
export type ProjectDetail = Schema['ProjectDetail']
export type StrategyProjectWorkspaceProjection = Schema['StrategyProjectWorkspaceProjection']
export type ControlJob = Schema['ControlJob']
export type ControlJobDetail = Schema['ControlJobDetail']
export type SuiteAction = Schema['SuiteActionValue']
export type ActiveResearchGateOverride = Schema['ActiveResearchGateOverride']
export type SuitePlan = Schema['SuitePlan']
export type SuiteLaunch = Schema['SuiteLaunch']
export type SuiteCancelResponse = Schema['SuiteCancelResponse']
export type AgentBrief = Schema['AgentBrief']
export type EvidenceRecord = Schema['EvidenceRecord']
export type EvidencePage = Schema['EvidencePage']
export type MlServiceStatus = Schema['MlServiceStatus']
export type MlExperimentPreflight = Schema['MlExperimentPreflight']
export type MlExperimentSummary = Schema['MlExperimentSummary']
export type MlExperimentPage = Schema['MlExperimentPage']
export type MlExperimentJobAccepted = Schema['MlExperimentJobAccepted']
export type MlTearSheetProjection = Schema['MlTearSheet']
