// Public aliases over the generated OpenAPI component definitions.

import type { components } from './generated'

type Schema = components['schemas']

export type RunListItem = Schema['RunListItem']
export type RunList = Schema['RunList']
export type RunDetail = Schema['RunDetail']
export type EquitySeries = Schema['EquitySeries']
export type ForecastSeries = Schema['ForecastSeries']
export type ForecastPaths = Schema['ForecastPaths']
export type NullTiers = Schema['NullTiers']
export type OptimTrials = Schema['OptimTrials']
export type PropfirmPaths = Schema['PropfirmPaths']
export type ForecastOrigins = Schema['ForecastOrigins']
export type Candle = Schema['Candle']
export type Candles = Schema['Candles']
export type ParamSpec = Schema['ParamDefinition']
export type StrategyDef = Schema['StrategyDefinition']
export type CommandOption = Schema['CommandOption']
export type CommandArg = Schema['CommandArgument']
export type CommandDef = Schema['CommandDefinition']
export type JobSummary = Schema['JobSummary']
export type JobDetail = Schema['JobDetail']
export type WorkspaceMeta = Schema['WorkspaceMeta']
export type WorkspaceDoc = Schema['WorkspaceDocument']
export type RiskScenario = Schema['RiskScenario']
export type RiskReport = Schema['RiskReport']
export type ScreenerQuote = Schema['ScreenerQuote']
export type ScreenerNewsItem = Schema['ScreenerNewsItem']
export type ScreenerNews = Schema['ScreenerNews']
export type ResearchRow = Schema['ResearchRow']
export type ResearchReport = Schema['ResearchReport']
export type OptionGreeks = Schema['OptionGreeks']
export type OptionCurvePoint = Schema['OptionCurvePoint']
export type OptionCurve = Schema['OptionCurve']
export type ProviderCredential = Schema['CredentialStatus']
export type ProviderOption = Schema['ProviderOption']
export type ProviderDefinition = Schema['ProviderDefinition']
export type SystemStatus = Schema['SystemStatus']
export type JsonScalar = Schema['JsonScalar']
export type PaperSession = Schema['PaperSession']
export type PaperStatus = PaperSession['status']
export type PaperEvent = Schema['PaperEvent']
export type PaperEventType = PaperEvent['event_type']
export type PaperJobSummary = JobSummary

// Intentionally opaque: trade schemas vary by engine and remain manifest-adjacent rows.
export type TradeRow = Record<string, string | number | null>
