"""Emit the five docs/atlas markdown views from the generated graph payload.

Progressive disclosure is a hard rule: each file opens with a short prose
overview and one small diagram (≤ MAX_DIAGRAM_NODES nodes — the emitter fails
rather than render an unreadable graph); enumerations live in collapsible
<details> sections. Every mermaid block is preceded by a `<!-- nodes: ... -->`
comment naming the raw node ids it draws, so the consistency test can prove
the docs never mention a node the graph does not contain, and is followed by
a plain-text fallback for renderers without mermaid.
"""

from __future__ import annotations

from typing import Any

from alpha_atlas.core.model import AtlasError

GENERATED_HEADER = (
    "<!-- GENERATED by alpha-atlas — do not edit; "
    "run: cd tools/alpha-atlas && uv run python -m alpha_atlas.generate -->"
)

MAX_DIAGRAM_NODES = 40

DOC_PATHS: tuple[str, ...] = (
    "docs/atlas/system-map.md",
    "docs/atlas/research-flow.md",
    "docs/atlas/data-lineage.md",
    "docs/atlas/frontend-flow.md",
    "docs/atlas/cli-flow.md",
)

_UI_HINT = (
    "Interactive exploration (evidence provenance, excerpts, prompt packs): "
    "`cd tools/alpha-atlas && uv run alpha-atlas` → http://127.0.0.1:8803"
)


def _label(text: str) -> str:
    return text.replace('"', "'")


def _diagram(
    nodes: list[tuple[str, str]], edges: list[tuple[str, str, str]], direction: str = "LR"
) -> str:
    """One capped mermaid block: (id, label) nodes, (source, target, label) edges."""
    if len(nodes) > MAX_DIAGRAM_NODES:
        raise AtlasError(
            f"diagram exceeds the {MAX_DIAGRAM_NODES}-node cap ({len(nodes)}); "
            "split the view instead of emitting an unreadable graph"
        )
    alias = {node_id: f"n{i}" for i, (node_id, _) in enumerate(nodes)}
    lines = [f"flowchart {direction}"]
    lines += [f'    {alias[node_id]}["{_label(label)}"]' for node_id, label in nodes]
    fallback: list[str] = []
    for source, target, edge_label in edges:
        if source not in alias or target not in alias:
            continue
        arrow = f"-- {_label(edge_label)} -->" if edge_label else "-->"
        lines.append(f"    {alias[source]} {arrow} {alias[target]}")
        fallback.append(f"{source} -> {target}" + (f"  [{edge_label}]" if edge_label else ""))
    id_comment = "<!-- nodes: " + "|".join(node_id for node_id, _ in nodes) + " -->"
    fallback_lines = fallback if fallback else [node_id for node_id, _ in nodes]
    return "\n".join(
        [
            id_comment,
            "```mermaid",
            *lines,
            "```",
            "",
            "<details><summary>Text fallback</summary>",
            "",
            "```",
            *fallback_lines,
            "```",
            "",
            "</details>",
        ]
    )


def _details(summary: str, body_lines: list[str]) -> str:
    return "\n".join([f"<details><summary>{summary}</summary>", "", *body_lines, "", "</details>"])


def _by_kind(payload: dict[str, Any], kind: str) -> list[dict[str, Any]]:
    return [n for n in payload["nodes"] if n["kind"] == kind]


def _edges(payload: dict[str, Any], edge_type: str) -> list[dict[str, Any]]:
    return [e for e in payload["edges"] if e["type"] == edge_type]


def _system_map(payload: dict[str, Any]) -> str:
    components = _by_kind(payload, "component")
    modules = {n["id"]: n for n in _by_kind(payload, "module")}
    component_of = {m["id"]: m.get("component") for m in modules.values()}
    deps: set[tuple[str, str]] = set()
    for edge in _edges(payload, "depends_on"):
        source_component = component_of.get(edge["source"])
        target_component = component_of.get(edge["target"])
        if source_component and target_component and source_component != target_component:
            deps.add((f"component:{source_component}", f"component:{target_component}"))
    contracts = _by_kind(payload, "contract")
    unknowns = sorted(n["id"] for n in payload["nodes"] if n["evidence"]["level"] == "unknown")
    stale = sorted(
        n["id"] for n in payload["nodes"] if n.get("meta", {}).get("needs_reverification")
    )
    node_list = [(c["id"], c["label"]) for c in sorted(components, key=lambda c: str(c["id"]))]
    contract_rows = [
        f"| {c['label']} | `{', '.join(c['meta']['source_modules'])}` | "
        f"`{', '.join(c['meta']['forbidden_modules'])}` |"
        for c in sorted(contracts, key=lambda c: str(c["id"]))
    ]
    parts = [
        GENERATED_HEADER,
        "",
        "# System map",
        "",
        f"{len(components)} components (packages, apps, workers), "
        f"{len(modules)} Python modules, {len(contracts)} import-linter contracts. "
        "Arrows aggregate module-level imports to component level; the contracts "
        "table is the enforced DAG. " + _UI_HINT,
        "",
        _diagram(node_list, sorted((s, t, "") for s, t in deps)),
        "",
        "## Enforced contracts",
        "",
        _details(
            f"{len(contracts)} import-linter forbidden contracts",
            ["| Contract | Sources | Forbidden |", "|---|---|---|", *contract_rows],
        ),
        "",
        "## Unknowns review queue",
        "",
        f"{len(unknowns)} node(s) with no documentation anchor, validating test, or "
        "cross-layer link — candidates for documentation or removal, never silently "
        "promoted:",
        "",
        _details(f"{len(unknowns)} unknown-level node(s)", [f"- `{i}`" for i in unknowns]),
        "",
    ]
    if stale:
        parts += [
            "## Needs re-verification",
            "",
            _details(
                f"{len(stale)} curated node(s) whose code anchors changed",
                [f"- `{i}`" for i in stale],
            ),
            "",
        ]
    return "\n".join(parts)


def _research_flow(payload: dict[str, Any]) -> str:
    lifecycle = sorted(_by_kind(payload, "workflow_node"), key=lambda n: int(n["meta"]["order"]))
    spine = [(lifecycle[i]["id"], lifecycle[i + 1]["id"], "") for i in range(len(lifecycle) - 1)]
    rows = []
    for node in lifecycle:
        anchors = node["meta"].get("verified_anchors", [])
        anchor = f"`{anchors[0]['path']}:{anchors[0]['line']}`" if anchors else "—"
        rows.append(
            f"| {node['label']} | {anchor} | {node['evidence']['level']} | "
            f"{node['meta']['purpose']} |"
        )
    return "\n".join(
        [
            GENERATED_HEADER,
            "",
            "# Research flow",
            "",
            "The governed lifecycle from raw observation to strategy promotion "
            "(spec §13, ADR-0019..0027). Every step below carries a computed evidence "
            "level and a verified primary code anchor. " + _UI_HINT,
            "",
            _diagram([(n["id"], n["label"]) for n in lifecycle], spine),
            "",
            "## Steps",
            "",
            "| Step | Primary anchor | Evidence | Purpose |",
            "|---|---|---|---|",
            *rows,
            "",
        ]
    )


def _data_lineage(payload: dict[str, Any]) -> str:
    entity_kinds = (
        "research_case",
        "hypothesis",
        "dataset",
        "experiment",
        "decision",
        "strategy_version",
    )
    entities = [n for n in payload["nodes"] if n["kind"] in entity_kinds]
    artifacts = _by_kind(payload, "artifact")
    ids = {n["id"] for n in entities} | {n["id"] for n in artifacts}
    chain_edges = [
        (e["source"], e["target"], e["type"])
        for e in payload["edges"]
        if e["type"] in ("depends_on", "produces") and e["source"] in ids and e["target"] in ids
    ]
    everything = sorted(entities + artifacts, key=lambda n: str(n["id"]))
    nodes = [(n["id"], n["label"]) for n in everything]
    artifact_rows = [
        f"| {a['label']} | {a['meta'].get('artifact_type', '')} | {a['evidence']['level']} |"
        for a in sorted(artifacts, key=lambda a: str(a["id"]))
    ]
    return "\n".join(
        [
            GENERATED_HEADER,
            "",
            "# Data lineage",
            "",
            "The research-entity chain (type-level in v1): Research Case → Hypothesis → "
            "Dataset → Experiment → Decision → Strategy Version, with the artifacts each "
            "workflow step produces. " + _UI_HINT,
            "",
            _diagram(nodes, sorted(chain_edges)),
            "",
            "## Artifacts",
            "",
            "| Artifact | Type | Evidence |",
            "|---|---|---|",
            *artifact_rows,
            "",
        ]
    )


def _frontend_flow(payload: dict[str, Any]) -> str:
    screens = sorted(_by_kind(payload, "screen"), key=lambda n: str(n["id"]))
    panels = {n["id"]: n for n in _by_kind(payload, "panel")}
    panel_screens: dict[str, list[str]] = {}
    for edge in _edges(payload, "part_of"):
        if edge["source"] in panels and edge["target"].startswith("screen:"):
            panel_screens.setdefault(edge["target"], []).append(edge["source"])
    panel_routes: dict[str, list[str]] = {}
    for edge in _edges(payload, "calls"):
        if edge["source"] in panels:
            panel_routes.setdefault(edge["source"], []).append(edge["target"])
    screen_nodes = [
        (s["id"], f"{s['meta'].get('label', s['label'])} ({len(panel_screens.get(s['id'], []))})")
        for s in screens
    ]
    sections = []
    for screen in screens:
        rows = []
        for panel_id in sorted(panel_screens.get(screen["id"], [])):
            targets = sorted(panel_routes.get(panel_id, []))
            routes = ", ".join(f"`{r.removeprefix('route:')}`" for r in targets)
            rows.append(f"| {panels[panel_id]['label']} | {routes or '—'} |")
        sections.append(
            _details(
                f"{screen['meta'].get('label', screen['label'])} — panels and routes",
                ["| Panel | Calls |", "|---|---|", *rows],
            )
        )
    return "\n".join(
        [
            GENERATED_HEADER,
            "",
            "# Frontend flow",
            "",
            f"{len(screens)} Workstation screens, {len(panels)} panel components, "
            "joined to their API routes via the fail-loud client.ts scan. " + _UI_HINT,
            "",
            _diagram(screen_nodes, []),
            "",
            "## Screens",
            "",
            *sections,
            "",
        ]
    )


def _cli_flow(payload: dict[str, Any]) -> str:
    commands = _by_kind(payload, "cli_command")
    leaves = [n for n in commands if not n["meta"].get("group")]
    mcp_calls = [e for e in _edges(payload, "calls") if e["source"].startswith("mcp:")]
    group_modules = {
        e["source"]: e["target"]
        for e in _edges(payload, "calls")
        if e["source"].startswith("cli:") and e["target"].startswith("module:")
    }
    group_ids = sorted({(n["id"]) for n in commands if n["meta"].get("group")})
    diagram_nodes = [(gid, gid.removeprefix("cli:alpha ")) for gid in group_ids]
    sections = []
    for gid in group_ids:
        prefix = gid.removeprefix("cli:") + " "
        rows = [
            f"| `{leaf['label']}` | "
            f"{', '.join('`' + o + '`' for o in leaf['meta']['options'][:6]) or '—'} |"
            for leaf in sorted(leaves, key=lambda n: str(n["id"]))
            if leaf["label"].startswith(prefix)
        ]
        module = group_modules.get(gid, "")
        module_note = f" → {module.removeprefix('module:')}" if module else ""
        summary = gid.removeprefix("cli:") + module_note
        sections.append(_details(summary, ["| Command | Options |", "|---|---|", *rows]))
    return "\n".join(
        [
            GENERATED_HEADER,
            "",
            "# CLI flow",
            "",
            f"{len(leaves)} leaf commands in {len(group_ids)} groups (from the committed "
            f"`alpha info commands` cache); {len(mcp_calls)} MCP action tools bridge to CLI "
            "leaves via argv literals. " + _UI_HINT,
            "",
            _diagram(diagram_nodes, []),
            "",
            "## Groups",
            "",
            *sections,
            "",
        ]
    )


def emit_docs(payload: dict[str, Any]) -> dict[str, str]:
    builders = {
        "docs/atlas/system-map.md": _system_map,
        "docs/atlas/research-flow.md": _research_flow,
        "docs/atlas/data-lineage.md": _data_lineage,
        "docs/atlas/frontend-flow.md": _frontend_flow,
        "docs/atlas/cli-flow.md": _cli_flow,
    }
    return {path: builders[path](payload) + "\n" for path in DOC_PATHS}
