import { expect, test } from '@playwright/test'
import { preparePage } from './support/workstationHarness'
const bars = Array.from({ length: 500 }, (_, i) => ({ t: 1700000000 + i * 86400, o: 100 + i, h: 102 + i, l: 99 + i, c: 101 + i, v: 1000 }))
test('direct UTC windows link without source requests or chart reconstruction', async ({ page }) => {
  await preparePage(page, { candles: { 'XRP/USDT': bars } })
  let requests = 0; page.on('request', r => { if (r.url().includes('/api/candles/')) requests++ })
  await page.goto('/#page=data&pane=PriceChart')
  const primary = page.locator('[data-panel-id=primary]'), host = primary.locator('.scientific-series-host').first()
  await expect(host.locator('canvas').first()).toBeVisible()
  await host.locator('canvas').first().evaluate(n => n.setAttribute('data-explore-lifetime', 'retained'))
  await page.getByLabel('Analytical layout').selectOption('side-by-side')
  await page.getByText('Panels', { exact: true }).click(); await page.getByLabel('Link UTC ranges').check(); await page.getByText('Panels', { exact: true }).click()
  const peer = page.locator('[data-panel-id=panel-1] .scientific-series-host').first()
  await expect(peer.locator('canvas').first()).toBeVisible()
  const before = requests
  await primary.getByRole('button', { name: '30D', exact: true }).first().click()
  const end = bars.at(-1)!.t
  await expect.poll(() => host.getAttribute('data-visible-range')).toBe(JSON.stringify({ from: end - 30 * 86400, to: end }))
  await expect.poll(() => peer.getAttribute('data-visible-range')).toBe(await host.getAttribute('data-visible-range'))
  await primary.locator('.scientific-coverage > summary').first().click()
  await expect(primary.locator('.scientific-coverage').first()).toContainText('500 observations · 0 missing')
  await expect(primary.locator('.scientific-coverage').first()).toContainText('Summary of the full returned series')
  await primary.locator('.scientific-coverage > summary').first().click()
  await primary.locator('.scientific-window > summary').first().click()
  await primary.getByLabel('Chart start date UTC').fill('2024-01-01'); await primary.getByLabel('Chart end date UTC').fill('2024-01-31')
  await primary.getByRole('button', { name: 'Apply window' }).click()
  await expect.poll(() => host.getAttribute('data-visible-range')).toBe(JSON.stringify({ from: Date.parse('2024-01-01T00:00:00Z') / 1000, to: Date.parse('2024-01-31T23:59:59Z') / 1000 }))
  await primary.locator('.scientific-window > summary').first().click()
  await primary.getByRole('button', { name: 'All data', exact: true }).first().click()
  await expect.poll(async () => JSON.parse((await host.getAttribute('data-visible-range'))!).from).toBe(bars[0].t)
  await expect(host.locator('canvas[data-explore-lifetime=retained]')).toHaveCount(1)
  expect(requests).toBe(before)
  await primary.locator('.scientific-cursor-data > summary').first().click()
  const bounds = (await host.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await expect(primary.locator('.scientific-cursor-data .cursor-values').first()).toContainText(' · O ')
  await expect(primary.locator('.scientific-cursor-data .cursor-values').first()).toContainText(' · V 1000')
  await expect.poll(async () => Math.abs((await host.locator('canvas').first().boundingBox())!.height - (await host.boundingBox())!.height)).toBeLessThanOrEqual(2)
  for (const plot of await page.locator('.scientific-series-host').all()) await expect(plot).toHaveAttribute('data-native-lod', 'idle')
  await page.screenshot({ path: `/tmp/alpha-chart-exploration-${test.info().project.name}.png` })
})
test('recorded tables expose missing values, pages and exact full-series export', async ({ page }) => {
  await preparePage(page)
  const run = 'd'.repeat(16), points = Array.from({ length: 205 }, (_, i) => ({ ts: 1700000000 + i * 86400, window: 20, sharpe: i === 204 ? null : i - 3, volatility: .2 }))
  await page.route('**/api/runs?limit=100', route => route.fulfill({ json: { items: [{ run_id: run, display_name: 'Recorded values fixture' }] } }))
  await page.route(`**/api/runs/${run}`, route => route.fulfill({ json: { run_id: run, display_name: 'Recorded values fixture', kind: 'backtests', manifest: {}, has_equity: false, has_trades: false, has_tearsheet: false } }))
  await page.route(`**/api/runs/${run}/native-tearsheet?*`, route => route.fulfill({ json: { rolling: points, provenance: { run_id: run }, bounds: { rolling: { original: 205, returned: 205, sampling: 'all', truncated: false } } } }))
  await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Replace panel primary').selectOption('sharpe')
  await page.getByRole('button', { name: 'Source', exact: true }).click(); await page.getByLabel('Panel recorded run').selectOption(run)
  await page.locator('.recorded-values > summary').click()
  await expect(page.locator('.recorded-values')).toContainText('1–100 / 205 · Page 1/3')
  await page.getByRole('button', { name: 'Next recorded values page' }).click(); await page.getByRole('button', { name: 'Next recorded values page' }).click()
  await expect(page.locator('.recorded-values')).toContainText('201–205 / 205 · Page 3/3')
  await expect(page.locator('.recorded-values table')).toContainText('Unavailable')
  await page.getByText('Sampling and provenance', { exact: true }).click()
  await expect(page.getByRole('table', { name: 'Recorded projection sampling' })).toContainText('205 / 205')
  await expect(page.getByRole('table', { name: 'Recorded projection sampling' })).toContainText('All values')
  await page.getByText('Sampling and provenance', { exact: true }).click()
  const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download exact recorded CSV' }).click()
  const download = await pending, stream = await download.createReadStream(); const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  const csv = Buffer.concat(chunks).toString()
  expect(csv.split('\n')).toHaveLength(207)
  expect(csv).toContain('2023-11-14T22:13:20.000Z,-3\n')
  expect(csv).toContain(`${new Date(points.at(-1)!.ts * 1000).toISOString()},\n`)
})
test('empty workspace guides source selection and readable panel types', async ({ page }) => {
  await preparePage(page, { candles: {}, initialSymbol: null }); await page.goto('/#page=data&pane=PriceChart')
  await expect(page.getByLabel('Analytical layout')).toContainText('Four panels')
  await expect(page.getByLabel('Replace panel primary')).toContainText('Rolling Sharpe')
  await expect(page.locator('.analytical-title')).not.toContainText('Canonical · ·')
  await page.getByRole('button', { name: 'Choose chart source' }).click()
  await expect(page.getByRole('dialog', { name: 'Replace panel source' })).toBeVisible()
})
