import { openDeskTool } from './support/workstationHarness'
import { expect, test } from '@playwright/test'

test('real CLI conditions, scan drilldown and assistant context share recorded inputs', async ({ page, request, baseURL }) => {
  test.setTimeout(120_000)
  const name = `edge-${test.info().project.name}`
  const saved = await request.post('/api/rules', { data: { name, spec: { name, history: 5, long_when: [{ left: { source: 'close' }, op: '>', right: { value: 1 } }], short_when: [] } } })
  expect(saved.ok()).toBe(true)
  const record = await saved.json()
  const evaluated = await request.post('/api/rules/evaluate', { data: { rules_id: name, symbol: 'BTC/USDT', as_of: '2020-05-01' } })
  expect(evaluated.ok()).toBe(true)
  expect(await evaluated.json()).toMatchObject({ signal: 1, rules_sha256: record.sha256, as_of: '2020-05-01', authority: 'none' })
  const scan = await request.post('/api/scans', { data: { name, rules: name, symbols: ['BTC/USDT'] } })
  expect(scan.ok()).toBe(true)
  await page.goto('/#page=data&pane=PriceChart')
  await openDeskTool(page, 'Workspace results')
  const dock = page.getByRole('region', { name: 'Workspace results', exact: true })
  await dock.getByLabel('As of (optional)').fill('2020-05-01')
  await dock.getByRole('region', { name: 'Saved scans' }).locator('li').filter({ hasText: name }).getByRole('button', { name: 'Run', exact: true }).click()
  await dock.getByRole('table', { name: 'Scan results', exact: true }).getByRole('button', { name: 'BTC/USDT', exact: true }).click({ timeout: 60_000 })
  await expect(page.locator('.sym-input')).toHaveValue('BTC/USDT')
  await openDeskTool(page, 'Research tools')
  const checklist = page.getByRole('region', { name: 'Condition checklist' })
  await expect(checklist).toContainText('Long condition', { timeout: 60_000 })
  await expect(checklist).toContainText(record.sha256.slice(0, 12))
  await expect(checklist).toContainText('2020-05-01')
  await page.reload()
  await expect(page.getByRole('complementary', { name: 'Research tools', exact: true })).toBeVisible()
  await expect(dock).toBeVisible()
  await expect(checklist).toContainText(record.sha256.slice(0, 12), { timeout: 60_000 })
  const headers = { Origin: new URL(baseURL!).origin }
  const session = await request.post('/api/assistant/sessions', { headers, data: { context: { symbol: 'BTC/USDT', as_of: '2020-05-01T23:59:59.999999Z', rules_name: name, rules_sha256: record.sha256 } } })
  expect(session.ok(), await session.text()).toBe(true)
  const body = await session.json()
  expect(body.authority).toBe('none')
  expect(body.attachments.map((item: { ref: string }) => item.ref)).toContain('chart')
  const checked = await request.post(`/api/assistant/sessions/${body.session_id}/check`, { headers, data: {} })
  expect(checked.ok()).toBe(true)
  expect(await checked.json()).toMatchObject({ valid: true, context_hash: body.context_hash })
  const forbidden = await request.post('/api/assistant/sessions', { headers: { Origin: 'https://untrusted.example' }, data: { context: { symbol: 'BTC/USDT', as_of: '2020-05-01T23:59:59Z' } } })
  expect(forbidden.status()).toBe(403)
  const revised = await request.post('/api/rules', { data: { name, spec: { name, history: 5, long_when: [{ left: { source: 'close' }, op: '>', right: { value: 2 } }], short_when: [] } } })
  expect(revised.ok()).toBe(true)
  const stale = await request.post('/api/assistant/sessions', { headers, data: { context: body.context } })
  expect(stale.status()).toBe(422)
  expect(await stale.text()).toContain('Saved rules changed since the selected scan')
})
