import { expect, test } from '@playwright/test'
import { preparePage } from './support/workstationHarness'

test('indicator search, favourites and parameter edits preserve CLI specs', async ({ page }) => {
  await preparePage(page)
  await page.goto('/#page=data&pane=PriceChart')
  await page.getByRole('menuitem', { name: 'Insert', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Indicators…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Indicators', exact: true })
  await dialog.getByRole('textbox', { name: 'Search indicators' }).fill('sma:20')
  await dialog.getByRole('checkbox', { name: /^SMA 20\s/ }).check()
  await dialog.getByRole('button', { name: 'Favourite sma:20', exact: true }).click()
  await dialog.getByRole('button', { name: 'Edit sma:20 parameters' }).click()
  await dialog.getByLabel('Window', { exact: true }).fill('30')
  await dialog.getByRole('button', { name: 'Apply parameters' }).click()
  await dialog.getByRole('textbox', { name: 'Search indicators' }).fill('sma:30')
  await expect(dialog.getByRole('checkbox', { name: 'sma:30', exact: true })).toBeChecked()
  await dialog.getByRole('button', { name: 'Edit sma:30 parameters' }).click()
  await dialog.getByLabel('Window', { exact: true }).fill('1')
  await dialog.getByRole('button', { name: 'Apply parameters' }).click()
  await expect(dialog.getByRole('alert')).toContainText('at least 2')
  await dialog.getByRole('button', { name: 'Cancel edit' }).click()
  await dialog.getByRole('textbox', { name: 'Search indicators' }).fill('')
  await dialog.getByRole('button', { name: 'Favourites', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Favourite sma:20', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  const settings = await page.evaluate(() => JSON.parse(localStorage.getItem('alpha.settings') ?? '{}'))
  expect(settings.overlays.crypto.indicators).toContain('sma:30')
  expect(settings.overlays.crypto.indicators).not.toContain('sma:1')
})
