import { expect, test } from '@playwright/test'
import { preparePage } from './support/workstationHarness'
const candles = { 'XRP/USDT': Array.from({ length: 500 }, (_, i) => ({ t: 1700000000 + i * 86400, o: 100 + i, h: 102 + i, l: 99 + i, c: 101 + i, v: 1000 })) }
test('reference shell, four panels, resizing and maximize preserve chart lifetime', async ({ page }) => {
  await page.setViewportSize({ width: 1585, height: 991 })
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await preparePage(page, { candles }); await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Plot renderer').selectOption('market')
  await expect(page.locator('.price-panel .count')).toHaveText('500 bars')
  await expect(page.getByRole('menubar', { name: 'Terminal menu' })).toBeVisible()
  await page.locator('.price-host canvas').first().evaluate(node => node.setAttribute('data-lifetime', 'preserved'))
  await page.getByLabel('Grid', { exact: true }).click()
  await page.getByLabel('Analytical layout').selectOption('grid')
  await expect(page.locator('.analytical-panel')).toHaveCount(4)
  await expect(page.locator('[data-panel-id=primary] canvas[data-lifetime=preserved]')).toHaveCount(1)
  await page.getByRole('separator', { name: 'vertical panel splitter' }).focus(); await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('separator', { name: 'vertical panel splitter' })).toHaveAttribute('aria-valuenow', '55')
  await page.getByRole('button', { name: 'Maximize panel primary', exact: true }).click()
  const box = await page.locator('.panel-maximized').boundingBox()
  expect(box!.width).toBeGreaterThan(1570); expect(box!.height).toBeGreaterThan(930)
  await page.keyboard.press('Escape')
  await expect(page.locator('.panel-maximized')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Maximize panel primary', exact: true })).toBeFocused()
  await expect(page.locator('[data-panel-id=primary] canvas[data-lifetime=preserved]')).toHaveCount(1)
  for (const layout of ['single', 'side-by-side', 'stacked', 'three-row', 'grid']) {
    await page.getByLabel('Analytical layout').selectOption(layout)
    await expect(page.locator('[data-panel-id=primary] canvas[data-lifetime=preserved]')).toHaveCount(1)
  }
  await page.screenshot({ path: '/tmp/alpha-quant-workspace-reference.png', fullPage: true })
  expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(1585)
  await page.setViewportSize({ width: 720, height: 800 })
  await expect(page.locator('.analytical-panel').last()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(720)
})
test('recorded run panels remain useful when the frozen price snapshot is missing', async ({ page }) => {
  await preparePage(page, { candles })
  const run = 'a'.repeat(16)
  const rolling = [0, 1, 2].map(i => ({ ts: 1700000000 + i * 86400, window: 20, return_value: 0.01, volatility: 0.2, sharpe: i === 1 ? null : 0.7, gross_exposure: null, net_exposure: null, turnover: null, exposure_available: false, turnover_available: false }))
  await page.route(`**/api/runs/${run}`, route => route.fulfill({ json: { run_id: run, display_name: 'Recorded fixture', kind: 'backtests', manifest: {}, has_equity: true, has_trades: false, has_tearsheet: false, run_context_watermark: 'Standalone sandbox', research_gate_watermark: null } }))
  await page.route(`**/api/runs/${run}/chart-bundle?*`, route => route.fulfill({ status: 409, json: { detail: 'snapshot_unavailable' } }))
  await page.route(`**/api/runs/${run}/equity`, route => route.fulfill({ json: { ts: rolling.map(p => p.ts), equity: [1, 1.1, 1.05], drawdown: [0, 0, -0.045] } }))
  await page.route(`**/api/runs/${run}/native-tearsheet?*`, route => route.fulfill({ json: { available: true, rolling, calendar_returns: [{ year: 2023, month: 11, return_value: 0.1 }], histogram: [{ left: -0.1, right: 0, count: 2 }, { left: 0, right: 0.1, count: 3 }], qq: [{ theoretical: -1, sample: -0.1 }, { theoretical: 1, sample: 0.1 }], benchmark: [], exposure_turnover: [], bounds: { rolling: { original: 3, returned: 3, sampling: 'all', truncated: false } }, provenance: { run_id: run }, yearly_returns: [], trade_statistics: [] } }))
  await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Plot renderer').selectOption('market')
  await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.route('**/api/runs?limit=100', route => route.fulfill({ json: { items: [{ run_id: run, display_name: 'Recorded fixture' }] } }))
  // Reload the selector after routing the recorded library.
  await page.getByRole('button', { name: 'Close source selector' }).click(); await page.getByRole('button', { name: 'Source', exact: true }).click()
  await page.getByLabel('Panel recorded run').selectOption(run)
  await expect(page.locator('[data-panel-id=primary]')).toContainText('Frozen snapshot required')
  await page.getByText('Panels', { exact: true }).click()
  await page.getByRole('button', { name: 'Price / equity / drawdown / rolling Sharpe', exact: true }).click()
  await expect(page.locator('.scientific-series-host')).toHaveCount(3)
  await expect(page.locator('[data-panel-id=preset-3]')).toContainText('backend window 20')
  await page.locator('[data-panel-id=preset-3] summary').filter({ hasText: 'Recorded values' }).click()
  await expect(page.locator('[data-panel-id=preset-3] .recorded-values table.blotter')).toContainText('Unavailable')
  await page.getByLabel('Replace panel preset-3').selectOption('diagnostics')
  await expect(page.locator('[data-panel-id=preset-3] .scientific-cartesian-host')).toHaveCount(2)
  await expect(page.locator('[data-panel-id=preset-3] svg')).toHaveCount(1)
  await expect(page.locator('[data-panel-id=primary]')).toContainText('Frozen snapshot required')
})

test('changing chart type preserves the actual panned time range', async ({ page }) => {
  await preparePage(page, { candles }); await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Plot renderer').selectOption('market')
  await expect(page.locator('.price-panel .count')).toHaveText('500 bars')
  const host = page.locator('.price-host')
  await expect.poll(() => host.getAttribute('data-visible-range')).not.toBeNull()
  const initial = await host.getAttribute('data-visible-range')
  // The chart may attach its wheel handler a frame after the range first appears; retry the gesture.
  await host.hover()
  await expect(async () => {
    await page.mouse.wheel(0, -600)
    expect(await host.getAttribute('data-visible-range')).not.toBe(initial)
  }).toPass({ timeout: 5_000 })
  const range = await host.getAttribute('data-visible-range')
  await page.getByLabel('Line (closes)', { exact: true }).click()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))))
  await expect(host).toHaveAttribute('data-visible-range', range!)
})

test('comparisons stay pinned across canonical changes and linked gestures converge', async ({ page }) => {
  await preparePage(page, { candles: { ...candles, 'BTC/USDT': candles['XRP/USDT'] } })
  await page.route('**/api/symbols', route => route.fulfill({ json: { symbols: ['XRP/USDT', 'BTC/USDT'] } }))
  await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Plot renderer').selectOption('market')
  await expect(page.locator('.price-panel .count')).toHaveText('500 bars')
  await page.getByRole('button', { name: 'Duplicate panel primary' }).click()
  const primary = page.locator('[data-panel-id=primary]')
  const comparison = page.locator('[data-panel-id=panel-1]')
  await expect(comparison.locator('.sym-input')).toHaveValue('XRP/USDT')
  await page.getByRole('button', { name: 'Symbol, venue and timeframe' }).click()
  await page.getByRole('combobox', { name: 'Active asset' }).fill('BTC')
  await page.getByRole('option', { name: /^BTC\/USDT / }).click()
  await expect(primary.locator('.sym-input')).toHaveValue('BTC/USDT')
  await expect(comparison.locator('.sym-input')).toHaveValue('XRP/USDT')
  await page.getByText('Panels', { exact: true }).click()
  await page.getByLabel('Link UTC ranges').check()
  await page.getByLabel('Link UTC cursors').check()
  await page.getByText('Panels', { exact: true }).click()
  const host = primary.locator('.price-host')
  const peer = comparison.locator('.price-host')
  const beforeUTC = await host.getAttribute('data-utc-range')
  await host.hover(); await page.mouse.wheel(0, -500)
  await expect.poll(() => host.getAttribute('data-utc-range')).not.toBe(beforeUTC)
  await expect.poll(async () => (await host.getAttribute('data-utc-range')) === (await peer.getAttribute('data-utc-range'))).toBe(true)
  const stable = await peer.getAttribute('data-visible-range')
  await page.evaluate(() => new Promise<void>(resolve => { let frames = 0; const next = () => ++frames === 20 ? resolve() : requestAnimationFrame(next); requestAnimationFrame(next) }))
  await expect(peer).toHaveAttribute('data-visible-range', stable!)
  // A gesture on the formerly remote panel must become the next range authority.
  await peer.hover(); await page.mouse.wheel(0, 200)
  await expect.poll(() => peer.getAttribute('data-visible-range')).not.toBe(stable)
  await expect.poll(async () => (await host.getAttribute('data-utc-range')) === (await peer.getAttribute('data-utc-range'))).toBe(true)
  // Two-panel presets retain the canonical panel and pin their secondary source.
  await primary.getByRole('button', { name: 'Source', exact: true }).focus()
  await page.getByText('Panels', { exact: true }).click()
  await page.getByRole('button', { name: 'Chart / table', exact: true }).click()
  await expect(primary).toContainText('Canonical')
  await page.getByRole('button', { name: 'Symbol, venue and timeframe' }).click()
  await page.getByRole('combobox', { name: 'Active asset' }).fill('XRP')
  await page.getByRole('option', { name: /^XRP\/USDT / }).click()
  await expect(primary.locator('.sym-input')).toHaveValue('XRP/USDT')
  await expect(page.locator('[data-panel-id=preset-1] .sym-input')).toHaveValue('BTC/USDT')
})

test('a hidden panned market document survives opening another run report', async ({ page }) => {
  const { HEAVY_LIBRARY_RUN, openTask, heavyChartBundle } = await import('./support/workstationHarness')
  await preparePage(page, { candles, runs: [HEAVY_LIBRARY_RUN], chartBundle: heavyChartBundle() })
  await page.route(`**/api/runs/${HEAVY_LIBRARY_RUN.run_id}`, route => route.fulfill({ json: { run_id: HEAVY_LIBRARY_RUN.run_id, display_name: 'Recorded fixture', kind: 'runs', manifest: {}, has_equity: false, has_trades: false, has_tearsheet: false } }))
  let hiddenPriceRequests = 0
  await page.route(`**/api/runs/${HEAVY_LIBRARY_RUN.run_id}/chart-bundle?*`, route => { hiddenPriceRequests++; return route.fulfill({ status: 409, json: { detail: 'snapshot_unavailable' } }) })
  await page.goto('/#page=data&pane=PriceChart'); await page.getByLabel('Plot renderer').selectOption('market')
  await expect(page.locator('.price-panel .count')).toHaveText('500 bars')
  const host = page.locator('.price-host')
  await host.locator('canvas').first().evaluate(node => node.setAttribute('data-document-lifetime', 'preserved'))
  const initial = await host.getAttribute('data-visible-range')
  await host.hover(); await page.mouse.wheel(0, -600)
  await expect.poll(() => host.getAttribute('data-visible-range')).not.toBe(initial)
  const range = await host.getAttribute('data-visible-range')
  await openTask(page, 'Results', 'Run library')
  await page.getByRole('tree', { name: 'Navigator' }).locator('.tree-leaf').filter({ hasText: 'causal-fixture' }).click()
  await expect(page.locator('.document-tabs').getByRole('tab', { selected: true })).toContainText('Report')
  await page.locator('.document-tabs').getByRole('tab', { name: 'Price', exact: true }).click()
  await expect(host.locator('canvas[data-document-lifetime=preserved]')).toHaveCount(1)
  await expect(host).toHaveAttribute('data-visible-range', range!)
  expect(hiddenPriceRequests).toBe(0)
})
