import { expect, test } from '@playwright/test'
import { preparePage } from './support/workstationHarness'
import type { components } from '../src/api/generated'
const candles = { 'XRP/USDT': Array.from({ length: 1000 }, (_, i) => ({ t: 1700000000 + i * 3600, o: 100 + i / 20, h: 102 + i / 20, l: 99 + i / 20, c: 101 + i / 20, v: 1000 + i })) }
test('scientific Bokeh default, optional market renderer and mounted maximize', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await preparePage(page, { candles }); await page.goto('/#page=data&pane=PriceChart')
  await expect(page.getByLabel('Plot renderer')).toHaveValue('scientific')
  const host = page.locator('[data-panel-id=primary] .scientific-series-host').first()
  await expect(host.locator('canvas').first()).toBeVisible()
  await expect(page.getByRole('alert').filter({ hasText: 'Scientific plot unavailable' })).toHaveCount(0)
  const auxiliary = page.locator('[data-panel-id=primary] .scientific-indicator .scientific-series-host')
  await expect(auxiliary).toHaveCount(0)
  const auxiliarySummary = page.locator('[data-panel-id=primary] .scientific-market-details > summary')
  await auxiliarySummary.click()
  await expect(auxiliary.locator('canvas').first()).toBeVisible()
  await auxiliary.locator('canvas').first().evaluate(node => node.setAttribute('data-auxiliary-lifetime', 'preserved'))
  await auxiliarySummary.click()
  await expect(auxiliary.locator('canvas[data-auxiliary-lifetime=preserved]')).toHaveCount(1)
  await auxiliarySummary.click()
  await expect(auxiliary.locator('canvas[data-auxiliary-lifetime=preserved]')).toBeVisible()
  await auxiliarySummary.click()
  await host.locator('canvas').first().evaluate(node => node.setAttribute('data-lifetime', 'scientific'))
  await page.getByLabel('Analytical layout').selectOption('grid')
  await expect(page.locator('.analytical-panel')).toHaveCount(4)
  await page.getByRole('button', { name: 'Maximize panel primary', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(host.locator('canvas[data-lifetime=scientific]')).toHaveCount(1)
  await page.getByLabel('Grid', { exact: true }).click()
  await expect(host.locator('canvas[data-lifetime=scientific]')).toHaveCount(1)
  await page.screenshot({ path: '/tmp/alpha-scientific-workspace.png', fullPage: true })
  await page.getByLabel('Plot renderer').selectOption('market')
  await expect(page.locator('[data-panel-id=primary] .price-host canvas').first()).toBeVisible()
  expect(errors).toEqual([])
})
test('hourly source discovery and scientific UTC links preserve native identity', async ({ page }) => {
  await preparePage(page, { candles })
  const manifest = 'c'.repeat(64)
  const dataset: components['schemas']['ArchiveChartDataset'] = { schema_version: 1, provider: 'bybit', venue: 'bybit', market_type: 'linear', family: 'derivative_bars', instrument: 'XRPUSDT', base_asset: 'XRP', quote_asset: 'USDT', frequency: '1h', units: 'quote_price', timestamp_convention: 'interval_start_utc', manifest_id: manifest, manifest_ids: [manifest], manifest_count: 1, start: '2023-11-14T00:00:00Z', end: '2023-12-26T00:00:00Z', row_count: 1000, verification: 'metadata_only' }
  await page.route('**/api/chart-datasets', route => route.fulfill({ json: { datasets: [dataset] } }))
  await page.route('**/api/candles/XRPUSDT?*', route => { expect(new URL(route.request().url()).searchParams.get('manifest_id')).toBe(manifest); return route.fulfill({ json: { symbol: 'XRPUSDT', snapshot_id: null, paper_markers: [], bars: candles['XRP/USDT'], provenance: { source: 'bybit:derivative_bars', venue: 'bybit', timeframe: '1H', manifest_id: manifest, market_type: 'linear', volume_unit: 'base', history_kind: 'reconstructed_from_verified_archive', snapshot_id: null, provenance_sha256: manifest, receipt_id: null, knowledge_cutoff: null, quality_status: 'qualified' } } }) })
  await page.goto('/#page=data&pane=PriceChart'); await page.reload()
  await expect(page.getByRole('button', { name: '1H', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '1H', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose native timeframe source' }).getByRole('button', { name: 'Open XRPUSDT', exact: true }).click()
  await expect(page.locator('.terminal-titlebar')).toContainText('[XRPUSDT,1h]')
  await page.getByLabel('Analytical layout').selectOption('side-by-side')
  await page.getByText('Panels', { exact: true }).click(); await page.getByLabel('Link UTC ranges').check(); await page.getByLabel('Link UTC cursors').check(); await page.getByText('Panels', { exact: true }).click()
  const primary = page.locator('[data-panel-id=primary] .scientific-series-host').first(), peer = page.locator('[data-panel-id=panel-1] .scientific-series-host').first()
  await expect(peer.locator('canvas').first()).toBeVisible()
  const initial = await primary.getAttribute('data-visible-range')
  const box = (await primary.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.wheel(0, -200)
  await expect.poll(() => primary.getAttribute('data-visible-range')).not.toBe(initial)
  await expect.poll(() => peer.getAttribute('data-visible-range')).toBe(await primary.getAttribute('data-visible-range'))
  const primaryReadout = page.locator('[data-panel-id=primary] .plot-readout').first(), peerReadout = page.locator('[data-panel-id=panel-1] .plot-readout').first()
  await page.mouse.move(box.x + box.width / 2 + 10, box.y + box.height / 2)
  await expect(primaryReadout).not.toContainText('Cursor —')
  await expect(peerReadout).toHaveText((await primaryReadout.textContent())!)
  // The imperative cursor must follow Bokeh's frame after linked zoom and relayout.
  const cursorGeometry = async (host: typeof primary) => {
    await expect(host.locator('.scientific-cursor')).toBeVisible()
    await expect.poll(async () => {
      const bounds = (await host.boundingBox())!, cursor = (await host.locator('.scientific-cursor').boundingBox())!
      return cursor.x >= bounds.x && cursor.x <= bounds.x + bounds.width && cursor.y >= bounds.y && cursor.y + cursor.height <= bounds.y + bounds.height + 1 && cursor.height > bounds.height / 2
    }).toBe(true)
  }
  await cursorGeometry(primary); await cursorGeometry(peer)
  const range = await primary.getAttribute('data-visible-range')
  await page.getByRole('button', { name: 'Maximize panel primary', exact: true }).click()
  await expect.poll(async () => (await primary.boundingBox())!.width).toBeGreaterThan(1200)
  const settled = async () => expect.poll(async () => Math.abs((await primary.locator('canvas').first().boundingBox())!.width - (await primary.boundingBox())!.width)).toBeLessThanOrEqual(2)
  await settled()
  let resized = (await primary.boundingBox())!
  await page.mouse.move(resized.x + resized.width / 2, resized.y + resized.height / 2)
  await cursorGeometry(primary)
  await page.keyboard.press('Escape')
  await expect(page.locator('.panel-maximized')).toHaveCount(0)
  await settled()
  resized = (await primary.boundingBox())!
  await page.mouse.move(resized.x + resized.width / 2, resized.y + resized.height / 2)
  await cursorGeometry(primary); await cursorGeometry(peer)
  expect(await primary.getAttribute('data-visible-range')).toBe(range)
  await page.getByRole('menuitem', { name: 'File', exact: true }).hover()
  await expect(peerReadout).toContainText('Cursor —')
})
