"""Generate/check the exhaustive OpenAPI verification and surface-authority inventory."""

from __future__ import annotations

import argparse
import ast
import json
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parents[1]
OPENAPI = ROOT / "apps/alpha-web/frontend/openapi.json"
CLASSIFICATION = ROOT / "docs/governance/openapi-operation-classification.json"
MATRIX = ROOT / "docs/governance/capability-authority-matrix.md"
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def _classification(method: str, path: str, operation: dict[str, Any]) -> tuple[str, str]:
    if path == "/api/providers/{provider_id}/check":
        return (
            "excluded",
            "Requires an explicitly injected provider credential or local broker gateway; "
            "covered by redacted receipt contract tests.",
        )
    if path.endswith("/stream") or path == "/api/activity/stream":
        return "fixture_backed", "SSE lifecycle is exercised with deterministic local job fixtures."
    required_parameters = any(
        bool(parameter.get("required")) for parameter in operation.get("parameters", [])
    )
    if method == "GET" and "{" not in path and not required_parameters:
        return "automatic", "Safe read exercised against an isolated temporary store."
    if method == "GET":
        return (
            "fixture_backed",
            "Parameterized safe read uses typed identity and boundary fixtures.",
        )
    if path.startswith("/api/owner-auth/"):
        return (
            "fixture_backed",
            "WebAuthn ceremony uses deterministic authenticator fixtures; real Touch ID is an "
            "owner walkthrough checkpoint.",
        )
    if "/literature/" in path:
        return (
            "fixture_backed",
            "Discovery/acquisition uses isolated lawful-response and hostile-document fixtures "
            "with vendor network disabled.",
        )
    return (
        "fixture_backed",
        "Mutation is exercised with deterministic local fixtures and no vendor network.",
    )


def operation_rows() -> list[dict[str, str]]:
    spec: dict[str, Any] = json.loads(OPENAPI.read_text(encoding="utf-8"))
    rows: list[dict[str, str]] = []
    for path, operations in sorted(spec["paths"].items()):
        for method, operation in sorted(operations.items()):
            if method not in HTTP_METHODS:
                continue
            mode, reason = _classification(method.upper(), path, operation)
            rows.append(
                {
                    "method": method.upper(),
                    "path": path,
                    "operation_id": str(operation["operationId"]),
                    "mode": mode,
                    "reason": reason,
                }
            )
    return rows


def mcp_tool_names() -> list[str]:
    source = ROOT / "apps/alpha-mcp/src/alpha_mcp/server.py"
    tree = ast.parse(source.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            call = decorator if isinstance(decorator, ast.Call) else None
            function = call.func if call else decorator
            if (
                isinstance(function, ast.Attribute)
                and isinstance(function.value, ast.Name)
                and function.value.id == "mcp"
                and function.attr == "tool"
            ):
                names.append(node.name)
                break
    return sorted(names)


def rendered_classification() -> str:
    return (
        json.dumps(
            {"schema_version": 1, "operations": operation_rows()},
            sort_keys=True,
            indent=2,
            allow_nan=False,
        )
        + "\n"
    )


def rendered_matrix() -> str:
    rows = operation_rows()
    modes = Counter(row["mode"] for row in rows)
    tools = mcp_tool_names()
    header = (
        "| Surface | Manifest count | May read | May draft/non-authoritative mutate | "
        "Owner evidence authority | Broker/order authority |"
    )
    workstation = (
        f"| Workstation REST/UI | {len(rows)} operations | Yes, bounded | Yes, only typed routes; "
        f"{modes['fixture_backed']} fixture-backed | Only the closed Touch ID research-action "
        "service | None; generic jobs deny paper/broker/order commands |"
    )
    cli = (
        "| Trusted local CLI | command manifest generated by `alpha info commands` | Yes | Yes | "
        "Closed research lifecycle plus recovery; no browser impersonation | Paper paths remain "
        "separately gated; no live-capital route |"
    )
    mcp = (
        f"| MCP | {len(tools)} tools | Yes, bounded | Drafts, notes, projects, and jobs within "
        "their typed contracts | None: no Touch ID credential/challenge access and no research "
        "approve/decide/D2 authority | None |"
    )
    return f"""# Capability and authority matrix

This file is generated from the committed FastAPI OpenAPI document and the decorated MCP server
functions. Run `uv run python scripts/check_openapi_operations.py --write` after either manifest
changes; CI runs the same command without `--write`.

{header}
|---|---:|---|---|---|---|
{workstation}
{cli}
{mcp}

OpenAPI release classification: {modes["automatic"]} automatic safe reads,
{modes["fixture_backed"]} fixture-backed operations, and {modes["excluded"]} explicitly excluded
external checks. The exhaustive per-operation ledger is
[`openapi-operation-classification.json`](openapi-operation-classification.json).

State words are intentionally distinct: **stored** means bytes exist; **configured** means local
requirements are present; **verified** means a fresh explicit check receipt exists; **qualified**
means data passed its separate quality contract; **research evidence** means governed admission;
**paper-ready** means all typed acceptance predicates pass; **execution authority** remains a
separate opt-in and never follows from any earlier state.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = {CLASSIFICATION: rendered_classification(), MATRIX: rendered_matrix()}
    if args.write:
        for path, content in expected.items():
            path.write_text(content, encoding="utf-8")
        return
    stale = [
        str(path.relative_to(ROOT))
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if stale:
        raise SystemExit("stale generated operation documentation: " + ", ".join(stale))


if __name__ == "__main__":
    main()
