"""Chart-pattern detection: swing structure, triple taps, trendlines, order blocks, FVGs.

Pure geometry over OHLCV bars. This package deliberately contains **no statistics** — it reports
what it found and when that was knowable, and nothing about whether the finding is significant.
Interval estimation, controls and multiplicity live in ``alpha_validation``; composing the two is
the job of a research driver, which keeps both packages core-only under the architecture DAG.

Every detector records ``confirmed_index`` alongside ``index``: a fractal swing is not knowable
until ``lookback`` bars after it prints, and any entry taken at the swing itself is reading the
future. The ``bias_guard`` tests enforce this.
"""

from __future__ import annotations

from importlib.metadata import version

from alpha_patterns.context import (
    Direction,
    FairValueGap,
    OrderBlock,
    TrendState,
    distance_from_low,
    find_fair_value_gaps,
    find_order_blocks,
    trend_state_ma,
    trend_state_vwap,
)
from alpha_patterns.controls import MatchedControls, sample_matched_controls
from alpha_patterns.cycles import (
    Cycle,
    VarianceRatio,
    autocorrelation,
    dominant_cycle,
    hurst_exponent,
    hurst_random_walk_reference,
    rolling_autocorrelation,
    rolling_hurst,
    rolling_variance_ratio,
    variance_ratio,
)
from alpha_patterns.head_shoulders import (
    VARIANT_NAMES,
    HSConfig,
    HSEvent,
    ShoulderRule,
    detect_head_shoulders,
)
from alpha_patterns.indicators import (
    BOLLINGER_WINDOW,
    RSI_WINDOW,
    CalendarFeatures,
    LeadLag,
    bollinger_bandwidth,
    calendar_features,
    consolidation_length,
    cross_correlation_lags,
    log_returns,
    percentile_rank,
    realized_volatility,
    rolling_correlation,
    rolling_mean,
    rolling_std,
    rsi,
    volume_ratio,
)
from alpha_patterns.levels import (
    FIB_EXTENSIONS,
    FIB_RATIOS,
    FibGrid,
    fib_levels_at,
    nearest_fib_distance,
    round_levels,
    round_number_distance,
)
from alpha_patterns.oscillators import (
    MACD,
    Channel,
    DirectionalIndex,
    Ichimoku,
    Stochastic,
    chaikin_money_flow,
    directional_index,
    donchian_channel,
    ema,
    ichimoku,
    keltner_channel,
    macd,
    money_flow_index,
    on_balance_volume,
    squeeze,
    stochastic,
    typical_price,
    wilder_smooth,
    williams_r,
)
from alpha_patterns.series import (
    OHLCV,
    FloatArray,
    IntArray,
    atr,
    rolling_max,
    rolling_min,
    rolling_vwap,
    true_range,
)
from alpha_patterns.structure import (
    StructureBreak,
    break_of_structure,
    extreme_between,
    last_pivot_before,
    swing_sequence,
)
from alpha_patterns.swings import Swing, SwingKind, find_swings, swings_known_by
from alpha_patterns.synthetic import (
    WedgeTruth,
    geometric_brownian_series,
    inject_descending_trendline,
    inject_head_shoulders,
    inject_triple_tap,
    inject_wedge,
)
from alpha_patterns.trendline import (
    ALL_BREAK_RULES,
    BreakRule,
    Scale,
    Trendline,
    TrendlineBreak,
    TrendlineConfig,
    build_trendlines,
    find_breaks,
)
from alpha_patterns.triple_tap import (
    BandReference,
    Population,
    TripleTap,
    TripleTapConfig,
    detect_nth_taps,
    detect_triple_taps,
)
from alpha_patterns.wedge import (
    KIND_CODES,
    Wedge,
    WedgeConfig,
    WedgeKind,
    WedgePanel,
    detect_wedges,
    wedge_lines,
    wedge_panel,
)

__version__ = version("alpha-patterns")

__all__ = [
    "ALL_BREAK_RULES",
    "BOLLINGER_WINDOW",
    "BandReference",
    "BreakRule",
    "CalendarFeatures",
    "Channel",
    "Cycle",
    "Direction",
    "DirectionalIndex",
    "FIB_EXTENSIONS",
    "FIB_RATIOS",
    "FairValueGap",
    "FibGrid",
    "FloatArray",
    "HSConfig",
    "HSEvent",
    "Ichimoku",
    "IntArray",
    "KIND_CODES",
    "LeadLag",
    "MACD",
    "MatchedControls",
    "OHLCV",
    "OrderBlock",
    "Population",
    "RSI_WINDOW",
    "Scale",
    "ShoulderRule",
    "Stochastic",
    "StructureBreak",
    "Swing",
    "SwingKind",
    "TrendState",
    "Trendline",
    "TrendlineBreak",
    "TrendlineConfig",
    "TripleTap",
    "TripleTapConfig",
    "VARIANT_NAMES",
    "VarianceRatio",
    "Wedge",
    "WedgeConfig",
    "WedgeKind",
    "WedgePanel",
    "WedgeTruth",
    "__version__",
    "atr",
    "autocorrelation",
    "bollinger_bandwidth",
    "break_of_structure",
    "build_trendlines",
    "calendar_features",
    "chaikin_money_flow",
    "consolidation_length",
    "cross_correlation_lags",
    "cycles",
    "detect_head_shoulders",
    "detect_nth_taps",
    "detect_triple_taps",
    "detect_wedges",
    "directional_index",
    "distance_from_low",
    "dominant_cycle",
    "donchian_channel",
    "ema",
    "extreme_between",
    "fib_levels_at",
    "find_breaks",
    "find_fair_value_gaps",
    "find_order_blocks",
    "find_swings",
    "geometric_brownian_series",
    "hurst_exponent",
    "hurst_random_walk_reference",
    "ichimoku",
    "inject_descending_trendline",
    "inject_head_shoulders",
    "inject_triple_tap",
    "inject_wedge",
    "keltner_channel",
    "last_pivot_before",
    "levels",
    "log_returns",
    "macd",
    "money_flow_index",
    "nearest_fib_distance",
    "on_balance_volume",
    "oscillators",
    "percentile_rank",
    "realized_volatility",
    "rolling_autocorrelation",
    "rolling_correlation",
    "rolling_hurst",
    "rolling_max",
    "rolling_mean",
    "rolling_min",
    "rolling_std",
    "rolling_variance_ratio",
    "rolling_vwap",
    "round_levels",
    "round_number_distance",
    "rsi",
    "sample_matched_controls",
    "squeeze",
    "stochastic",
    "swing_sequence",
    "swings_known_by",
    "trend_state_ma",
    "trend_state_vwap",
    "true_range",
    "typical_price",
    "variance_ratio",
    "volume_ratio",
    "wedge_lines",
    "wedge_panel",
    "wilder_smooth",
    "williams_r",
]
