"""Committed Atlas outputs are internally consistent (pure JSON checks, stdlib-only).

Freshness is enforced only by the Atlas gate (owner decision 2026-08-20); this
guard catches committed rot: dangling references, schema drift, docs mentioning
nodes the graph does not contain, or a hand-edited generated file.
"""

from __future__ import annotations

import functools
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
GENERATED = ROOT / "architecture/atlas/generated"
DOCS = ROOT / "docs/atlas"
_DOC_NAMES = (
    "system-map.md",
    "research-flow.md",
    "data-lineage.md",
    "frontend-flow.md",
    "cli-flow.md",
)


@functools.cache
def _graph() -> dict[str, Any]:
    payload: dict[str, Any] = json.loads((GENERATED / "graph.json").read_text(encoding="utf-8"))
    return payload


def test_graph_matches_the_schema_enums() -> None:
    schema = json.loads(
        (ROOT / "architecture/atlas/schema/atlas-schema.json").read_text(encoding="utf-8")
    )
    kinds = set(schema["$defs"]["node_kind"]["enum"])
    levels = set(schema["$defs"]["evidence_level"]["enum"])
    edge_types = set(schema["$defs"]["edge_type"]["enum"])
    graph = _graph()
    node_ids = set()
    for node in graph["nodes"]:
        assert node["kind"] in kinds, node["id"]
        assert node["evidence"]["level"] in levels, node["id"]
        assert node["evidence"]["level"] != "observed", node["id"]  # Phase 7 reserved
        assert node["evidence"]["provenance"], node["id"]
        node_ids.add(node["id"])
    for edge in graph["edges"]:
        assert edge["type"] in edge_types, edge["id"]
        assert edge["source"] in node_ids, edge["id"]
        assert edge["target"] in node_ids, edge["id"]


def test_unknowns_view_matches_the_graph() -> None:
    graph = _graph()
    view = json.loads((GENERATED / "views/unknowns.json").read_text(encoding="utf-8"))
    expected = sorted(n["id"] for n in graph["nodes"] if n["evidence"]["level"] == "unknown")
    assert view["unknown_node_ids"] == expected
    assert view["inputs_hash"] == graph["inputs_hash"]


def test_curated_definitions_resolve_to_graph_nodes() -> None:
    graph_ids = {n["id"] for n in _graph()["nodes"]}
    for name in ("research-lifecycle.json", "data-lineage.json"):
        definitions = json.loads(
            (ROOT / "architecture/atlas/definitions" / name).read_text(encoding="utf-8")
        )
        for entry in definitions["nodes"]:
            assert entry["id"] in graph_ids, f"{name}: {entry['id']}"


def test_docs_are_generated_and_mention_only_real_nodes() -> None:
    graph_ids = {n["id"] for n in _graph()["nodes"]}
    for name in _DOC_NAMES:
        text = (DOCS / name).read_text(encoding="utf-8")
        assert text.startswith("<!-- GENERATED by alpha-atlas"), name
        for line in text.splitlines():
            if line.startswith("<!-- nodes: "):
                ids = line.removeprefix("<!-- nodes: ").removesuffix(" -->").split("|")
                missing = [i for i in ids if i not in graph_ids]
                assert not missing, f"{name}: {missing}"
